"Which players play in Panathnaikos ?"
"In which team does Calinic play?"
"What is the average performance of Round 2 ?"
"What are the average playing minutes for those players who had more than 20 performance in round 1?"
"What is the average performance of players in Barcelona?"
"What is the average performance of Vezenkov?"
"How much credits does Walkup cost ?"
"How much credits do all the players of Olympiacos cost ?"
"Provide the best five players based on this metric : performance"
"Given you have 100 available credits to spend, choose the best set of 10 players based on this metric : performance"
"Given you have 100 available credits to spend, choose the best set of 10 players based on this metric : performance"